global numStep;
t = 0:0.5:12;
b = [27 19 10 9 7 6.5 4 3.1 2.6 2.1 1 0.3 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]';

optimizationParameters = optimset('lsqnonlin');
optimizationParameters = optimset(optimizationParameters,...
    'GradObj', 'off', ...
    'Hessian', 'on', ...
    'Diagnostics', 'on', ...
    'TolFun', 4e-10, ...
    'MaxIter', 10e5, ...
    'Display', 'iter', ...
    'LevenbergMarquardt','off', ...
    'DiffMaxChange', 1e5, ...
    'DiffMinChange', 1e-5 ...
    );
modelName = 'model1';
%modelHandle = open([modelName '.mdl']);
lowerBounds = [0 0];
upperBounds = [10 10];
[t, x, simulatedDataInitial] =sim(modelName, 0:0.5:12);
figure(1);
subplot 211;
plot(simulatedDataInitial, 'r.');
hold on;
plot(b);
title(['Initial simulation']);

numStep = 0;
[params, resnorm] = lsqnonlin(@optimfun, ...
    [5, 0.8], ...
    lowerBounds, ...
    upperBounds, ...
    optimizationParameters, b, modelName)
